theme: jekyll-theme-midnight
title: Jacob Weidner






































external:
-{title: Mail, icon: envelope, url: "mailto:jacob.weidner@outlook.com"}
-{title: Github, icon: github, url: "https://github.com/Weidnerjf"}
