theme: jekyll-theme-midnight
title: Jacob Weidner































external:
 -{title: Mail, icon: envelope, url: "mailto:jacob.weidner@outlook.com"}
 -{title: Github, icon: envelope, url: "https:/github.com/WeidnerJF"}



